### ISSUE TITLE
เขียน assembly language program สั้นๆเกี่ยวกับ การคูณของเลข 2 จำนวน และการทำ recursive function

### ISSUE THREAD

**Issue by AutsadaWiriya** [Project-Computer-Architecture-67-AAAUPP/Project-Computer-Architecture-67-AAAUPP#3]

**Comment by pubestpubest** [comment]
@pubestpubest 
- เขียนฟังก์ชันในภาษา Assembly สำหรับการคูณของเลขสองจำนวน
- ฟังก์ชันนี้ต้องรับอินพุตเป็นจำนวนเต็มสองตัวและคืนค่าผลลัพธ์จากการคูณ
- หลีกเลี่ยงการใช้คำสั่งคูณระดับสูง ถ้าเป็นไปได้ ให้ใช้การคำนวณแบบพื้นฐาน เช่น การบวกซ้ำหรือการเลื่อนบิต (bit-shifting) เพื่อจำลองการคูณ
- มีการคอมเมนต์อธิบาย

@slyphstia , @Mxrch200x 
- เขียนฟังก์ชันแบบ Recursive ในภาษา Assembly เช่น การคำนวณแฟคทอเรียล (factorial) 
- มีการคอมเมนต์อธิบาย
